# Site settings
title: esnext.io
email: david@esnext.io
description: A place to learn the next generation of javascript.
baseurl: ""
url: "http://esnext.io"
twitter_username: davidrhyswhite
github_username: davidrhyswhite

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
